import type { NextPage } from "next";
import Head from "next/head";

import { Panel } from "@sextival/components/base";

// sections
import Hero from "@sextival/components/hero";
import About from "@sextival/components/about";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Sextival - Il festival della salute sessuale</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className={`h-screen w-screen scroll-smooth snap-y snap-mandatory overflow-y-scroll `}
      >
        <Hero />
        <About />
        <Panel>3</Panel>
        <Panel>4</Panel>
        <Panel isLastOne>5</Panel>
      </main>
    </>
  );
};

export default Home;
